menu/menu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu_university.urls', namespace='menu'))
]

menu/menu_university/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, include

from menu_university.views import (index, get_user,
                                   get_about, get_salary,
                                   get_scholarship)

app_name = 'menu'
urlpatterns = [
    path('', index, name='main_page'),
    path('auth/login/', get_user, name='login'),
    path('auth/logout/', LogoutView.as_view(
        template_name='registration/logged_out.html'), name='logout'),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', get_about, name='about'),
    path('scholar/', get_scholarship, name='scholar'),
    path('salary/', get_salary, name='salary')
]

menu/menu_university/forms.py
from django import forms


class UserForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())

menu/menu_university/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect

from menu_university.forms import UserForm
from menu_university.import_from_bd import (get_username,
                                            get_menu, get_about_user,
                                            get_sum_salary,
                                            get_sum_scholarship)


def index(request):
    if request.user.is_authenticated:
        context = {
            'username': get_username(request),
            'menu': get_menu(request)
        }
        return render(request, 'menu_university/index.html', context)
    return render(request, 'menu_university/index.html')


def get_user(request):
    form = UserForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            email = request.POST.get('email')
            password = request.POST.get('password')
            user = authenticate(request, username=email, password=password)
            login(request, user)
            return redirect('menu:main_page')
    context = {
        'form': form
    }
    return render(request, 'registration/login.html', context)


@login_required
def get_about(request):
    context = {
        'username': get_username(request),
        'menu': get_menu(request),
        'about': get_about_user(request)
    }
    return render(request, 'menu_university/about.html', context)


@login_required
def get_salary(request):
    context = {
        'username': get_username(request),
        'menu': get_menu(request),
        'salary': get_sum_salary(request)
    }
    return render(request, 'menu_university/salary.html', context)


@login_required
def get_scholarship(request):
    context = {
        'username': get_username(request),
        'menu': get_menu(request),
        'scholarship': get_sum_scholarship(request)
    }
    return render(request, 'menu_university/scholarship.html',  context)

menu/menu_university/templates/includes/header.html
{% load static %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    <meta charset="utf-8">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
    <title>Внутренняя система университета</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-light" style="background-color: #37B34A">
        <div class="container">
         <ul class="nav nav-pills">
          <li class="nav-item"> 
            <a class="nav-link link-light" href="{% url 'menu:main_page' %}">Главная страница</a>
          </li>
            {% if request.user.is_authenticated %}
            {% for key, value in menu.items %}
              {% with slug=value %}
              <li class="nav-item">
                <a class="nav-link link-light" href="{% url value %}">{{ key }}</a>
              </li>
              {% endwith %}
            {% endfor %}
            <li class="nav-item"> 
              <a class="nav-link link-light" href="{% url 'menu:logout' %}">Выйти</a>
            </li>
            <li>
              Пользователь: {{ username }}
            </li>
            {% else %}
            <li class="nav-item"> 
              <a class="nav-link link-light" href="{% url 'menu:login' %}">Войти</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>      
    </header> 
</body>
</html>

menu/menu_university/templates/menu_university/about.html
{% extends 'menu_university/base.html' %}

{% block title %} Внутренняя система университета {% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        О себе
      </div>
      {% if request.user.is_authenticated %}
      <div class="card-body">
          <p> {{ about }} </p>
      </div>
  {% endif %}
      </div>
  </div> 
</div>
 
{% endblock %}

menu/menu_university/templates/menu_university/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        {% include 'includes/header.html' %}
    </header>
    {% block content %}
    
    {% endblock %}
</body>
</html>

menu/menu_university/templates/menu_university/index.html
{% extends 'menu_university/base.html' %}

{% block title %} Внутренняя система университета {% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Главная страница
        </div>
        {% if request.user.is_authenticated %}
        <div class="card-body">
            <p> Выберите пункт меню </p>
        </div>
    {% else %}
        <div class="card-body">
            <p>Необходимо войти в систему</p>
        </div>
    {% endif %}
        </div>
    </div> 
</div>
 
{% endblock %}

menu/menu_university/templates/menu_university/salary.html
{% extends 'menu_university/base.html' %}

{% block title %} Внутренняя система университета {% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Зарплата
      </div>
      {% if request.user.is_authenticated %}
      <div class="card-body">
          <p> {{ salary }} </p>
      </div>
  {% endif %}
      </div>
  </div> 
</div>
 
{% endblock %}

menu/menu_university/templates/menu_university/scholarship.html
{% extends 'menu_university/base.html' %}

{% block title %} Внутренняя система университета {% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Стипендия
      </div>
      {% if request.user.is_authenticated %}
      <div class="card-body">
          <p> {{ scholarship }} </p>
      </div>
  {% endif %}
      </div>
  </div> 
</div>
 
{% endblock %}